# Generated by Django 5.1.1 on 2024-09-19 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accutatormodules',
            name='sensor_module',
            field=models.ForeignKey(blank=True, limit_choices_to={'module_type__ne': 'AM'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmapi.modules'),
        ),
        migrations.AlterField(
            model_name='historicalaccutatormodules',
            name='sensor_module',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'module_type__ne': 'AM'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='farmapi.modules'),
        ),
    ]
