# Generated by Django 5.1.1 on 2024-10-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accutatormodules',
            name='triggerValue',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalaccutatormodules',
            name='triggerValue',
            field=models.IntegerField(null=True),
        ),
    ]
