# Generated by Django 5.1.1 on 2024-09-19 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapi', '0002_alter_accutatormodules_sensor_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accutatormodules',
            name='sensor_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmapi.modules'),
        ),
        migrations.AlterField(
            model_name='historicalaccutatormodules',
            name='sensor_module',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='farmapi.modules'),
        ),
    ]
